### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by Greece2** [ardnew/ILI9341-Layout-Manager#1]
When trying to compile the example, I get the error message
from \libraries\ILI9341-Layout-Manager\examples\ilm-demo\ilm-demo.ino:10:
\libraries\ILI9341-Layout-Manager\src/obj/Primitive.h:22:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~

So, this <string> seems to be missing.
I'm using a MEGA2560, IDE is 1.8.13

Any idea what could be wrong ?

Thanks !

**Comment by Greece2** [comment]
In the "Primitive.h" I changed the "#include <string>" to #include <string.h>, that error is gone.
In the "Screen.h" I changed the #include <vector> to "include <vector.h>, that error is gone as well.
But I stiil get the error
"Screen.h:16:10: fatal error: array: No such file or directory
 #include <array>
          ^~~~~~~"
Changing array to array.h didn't help.

Any idea how to overcome all these errors ???

**Comment by Greece2** [comment]
Any chance to get this fixed or a reply ?

**Comment by ardnew** [comment]
It appears the older/traditional Arduino (AVR) toolchain does not implement a modern `stdc++` library. 

I suspect that even if you manage to find suitable replacement header files for each of the missing files, you might then face a linker error, as this project requires the `-lstdc++` flag passed to GCC, which will fail to resolve.

Sorry, this software was not written or intended for older (AVR) devices. It would take considerable refactoring effort to remove the `stdc++` dependency. If you are uncomfortable doing this, then unfortunately you will need to use a different device or a different library.

This library will only work on one of the ARM-based (Cortex-M0 and Cortex-M4F have been tested) Arduino devices or microcontrollers, like the Arduino Nano, Arduino Zero, Adafruit Metro, Adafruit ItsyBitsy, etc.

**Comment by Greece2** [comment]
Okay, thanks for the answer anyway. Though I wouldn't consider an ATmega2560 as an "older AVR device".
