### ISSUE TITLE
ERROR: #include<string>

### ISSUE THREAD

**Issue by kmsaleh** [ardnew/ILI9341-Layout-Manager#2]
using ILI934 TFT SHIELD WITH ARDUINO UNO, RUNNING THE EXAMPLE GIVES ERROR
![ERROR](https://user-images.githubusercontent.com/20566560/137347447-033cc171-443f-44b5-84ed-7609f2eb850c.jpg)
:

**Comment by ardnew** [comment]
The Arduino Uno is an AVR chip, so this is the same issue as the previously posted. See here for details: https://github.com/ardnew/ILI9341-Layout-Manager/issues/1
